CHANGELOG.md
demo/navigator_inside_tabbar/index.html
framework/directives/tab.js
framework/views/slidingMenu.js
framework/views/tabbarView.js

@anatoo さん
日本語のドキュメントをお願いします。後、このやり方で大丈夫だと思いますか？

Implemented "persistent" attribute for <ons-tab>.

---

CHANGELOG.md
demo/index.html
demo/pull_hook/index.html
framework/css/common.css
framework/directives/pullHook.js
framework/views/pullHook.js
framework/views/slidingMenu.js

@anatoo さん、
ons-pull-hookを実装しました。もし何か間違いがあれば言ってください。
ドキュメントの翻訳もお願いします。

Pull to refresh

---

CHANGELOG.md
demo/index.html
demo/lazy_repeat/index.html
framework/directives/lazyRepeat.js
framework/views/lazyRepeat.js
framework/views/pullHook.js
framework/views/tabbarView.js
test/manual-testcases/composition/02-pull-hook+lazy-repeat.html

@anatoo さん
iOSだとまだ問題があります。iOSでスクロールしている間、全然レンダリングしてくれないです。
強制的にレンダリングをさせてみましたが、どんな方法でもスクロールが終わってからレンダリングします。

Lazy repeat

---

framework/directives/lazyRepeat.js

remove an extra back quote

---

framework/lib/winstore-jscompat.js
gulpfile.js

This reverts commit cbab9af458186514ce0e9d6328b74b3e43a01c79.

Revert "Revert "External library added for Windows support""

---

framework/css/icon.css

This reverts commit e65a828d7bc3812677a237614164b9afa2a1e9e9.

Revert "Cleaned up icon spin animation."

---

framework/views/tabbarView.js

Fixed TabbarView.registerAnimator function.

Fixed issue #512.

---

framework/directives/tabBar.js
framework/views/tabbarView.js

Allow 'animation' option in TabbarView.setActiveTab(index, options) method.

Fixed issue #511.

---

framework/js/onsen.js
framework/views/pullHook.js

tested successfully in iOS, Android and Windows Phone 8.1

Hammer default behaviour change + pullHook fix

---

framework/directives/carousel.js

getAutoScrollRatio() should not receive any parameter.

Small fix for carousel docs

---

framework/directives/button.js

There was no "@param" in setDisabled function.

Small fix for ons-button docs

---

README.md
css-components/components-src/stylus/components/notification.styl

Notifications (badges) should be hidden if they have no content.
... and updated repo URL in README :wink:

Hide empty notifications

---

framework/views/dialog.js
test/e2e/composition/navigator+dialog.html
test/e2e/composition/scenarios.js

Fix broken dialog destructor.

---

CHANGELOG.md
framework/directives/modal.js
framework/views/fadeModalAnimator.js
framework/views/modal.js
framework/views/modalAnimator.js
test/manual-testcases/animationOptions/06-modal.html

@anatooさん、モーダルにアニメーションを追加しました。レビューをお願いいたします。

Added animation for ons-modal.

---

framework/views/iosSlideTransitionAnimator.js
framework/views/overlaySlidingMenuAnimator.js
framework/views/pushSlidingMenuAnimator.js

iosSlideTransitionAnimator :: remove unused var in _decompose()
overlaySlidingMenuAnimator :: remove unused var in _generateMenuPageStyle()
pushSlidingMenuAnimator :: remove used var in _generateBehindPageStyle()

Animators :: minor cleanup

---

framework/directives/pullHook.js
framework/views/pullHook.js

getPullDistance, getHeight, getThresholdHeight, getCurrentState

Implementation and docs for some functions of PullHook

---

CHANGELOG.md
framework/directives/ifPlatform.js

Could you update the Japanese translation? :)

if-platform now accepts multiple values

---

CHANGELOG.md
css-components/components-src/stylus/components/list.styl
framework/directives/listItem.js

min-height inherit
line-height inherit

list-item new modifier 'tight'

---

framework/directives/template.js
test/e2e/slidingMenu/index.html

Failing test.

---

core/elements/ons-bottom-toolbar.es6
core/elements/ons-button.es6
core/elements/ons-list-header.es6
core/elements/ons-list-item.es6
core/elements/ons-list.es6
core/elements/ons-page.es6
core/elements/ons-toolbar-button.es6
core/elements/ons-toolbar.es6
core/lib/modifier.es6
core/lib/modifier.spec.js
core/lib/ons-internal.es6
core/lib/ons-util.es6
framework/directives/backButton.js
framework/directives/bottomToolbar.js
framework/directives/button.js
framework/directives/list.js
framework/directives/listHeader.js
framework/directives/listItem.js
framework/directives/toolbar.js
framework/services/onsen.js
framework/views/generic.js
framework/views/iosSlideTransitionAnimator.js
framework/views/page.js

@argelius Merge this changes if there is no problem.

Added ons-toolbar element.

---

core/lib/ons-gesture-detector.js

Same code in Hammer.js: <a href="https://github.com/OnsenUI/OnsenUI/blob/1.3.2/framework/lib/hammer.js#L282">line 282</a>

ons-gesture-detector. Fixes #667

---

CHANGELOG.md
framework/views/navigator.js

insertPage bug. Fixes #691.

---

CHANGELOG.md
CONTRIBUTORS.md
core/css/scroller.css
framework/views/carousel.js

Fix for ons-scroller and ons-carousel. Closes #707

---

core/elements/ons-carousel.es6
core/elements/ons-col.spec.js
core/elements/ons-popover.es6
core/lib/fade-popover-animator.es6
core/lib/ons.es6
core/lib/popover-animator.es6
core/vendor/promise-6.1.0.js
demo/popover/index.html
framework/directives/backButton.js
framework/directives/popover.js
framework/directives/templates.js
framework/js/onsen.js
framework/templates/popover.tpl
framework/views/popover.js
framework/views/popoverAnimator.js
gulpfile.js

@argelius Merge this changes if there is no problem.

Added ons-popover custom element.

---

core/elements/ons-pull-hook.es6
framework/directives/pullHook.js
framework/views/pullHook.js

@argelius Merge this changes if there is no problem.

Added ons-pull-hook custom elements.

---

CHANGELOG.md
core/elements/ons-navigator.es6
core/elements/ons-navigator.spec.es6

Fixed the behaviour of `insertPage()` method when the provided index is higher or lower than the number of pages in the stack.

Navigator code coverage and minor fix

---

core/vendor/fastclick-patched.js

https://github.com/OnsenUI/OnsenUI/issues/872

fix(issue-872): Fixed fastclick stop to send click event after setting system clock back.

---

docs/package/tag-defs/index.js
docs/package/templates/directive.template.html
docs/package/templates/object.template.html

Added new doc comment tags:
* @extensionOf
* @initonly
@argelius Merge this changes if there is no problems.

Added @extensionOf and @initonly doc comment tags.

---

CHANGELOG.md
core/elements/ons-carousel.es6
framework/directives/carousel.js

@anatooさん
お時間のあるときに日本語のドキュメントをお願いします。

Expose carousel item count

---

core/elements/ons-navigator.es6
core/lib/navigator-page.es6
framework/directives/navigator.js
test/e2e/navigator/index.html
test/e2e/navigator/scenarios.js

Implemented this feature request: https://github.com/OnsenUI/OnsenUI/issues/931
@argelius Could you merge this changes if there is no problems?

Changed resetToPage() to accept empty parameters.

---

CHANGELOG.md
demo/carousel/index.html
framework/directives/scope.js
framework/services/onsen.js

This implements the `ons-scope` attribute:
https://github.com/OnsenUI/OnsenUI/issues/597

Add ons-scope attribute.

---

core/lib/alert-dialog-animator.es6
core/lib/animit.js
core/lib/dialog-animator.es6
core/lib/fade-navigator-transition-animator.es6
core/lib/fade-popover-animator.es6
core/lib/ios-slide-navigator-transition-animator.es6
core/lib/lift-navigator-transition-animator.es6
core/lib/simple-slide-navigator-transition-animator.es6
core/lib/tabbar-animator.es6

Added some performance optimization and refactoring on animit.js.
* Changed to use setImmediate() and requestAnimationFrame() on forcing synchronous layout for rendering performance.
* Renamed resetStyle() to restoreStyle() and added saveStyle() that have corresponding function.
* Animit object no longer use "data-animit-orig-style" attribute for saving style data. 
* Added some optimization on wait() method.
@argelius Please merge this if there is no problem.

Animit improved

---

CHANGELOG.md
core/elements/ons-back-button.es6
core/lib/ons-util.es6

@anatoo
This will change the style of the back button depending on if the parent toolbar has the "material" modifier or not.
Please merge if there is no trouble.

Material back button

---

core/lib/ons-notification.es6

@argelius Please merge this changes if there is no problem.

fix(ons-notification.alert()): Fixed #999.

---

css-components/components-src/stylus/components/alert-dialog.styl

@argelius Please merge this changes.

fix(css-components): Fixed #1001.

---

css-components/components-src/stylus/components/fab.styl
demo/ripple/index.html

@argelius Please merge this changes.

Fixed #1003.

---

framework/directives/speedDial.js
framework/directives/speedDialItem.js

@argelius Please add English doc-comments for this components and merge this PR.

docs(ons-speed-dial): Added Japanese doc-comments on ons-speed-dial and ons-speed-dial-item elements.

---

CHANGELOG.md
css-components/components-src/stylus/components/switch.styl

Update ios switch

---

core/elements/ons-back-button.es6
core/elements/ons-navigator.es6
core/lib/navigator-page.es6

@argelius Please review when you have some time.

fix(ons-back-button): auto hides on 'resetToPage()'. Closes #1100

---

core/elements/ons-navigator.es6

Navigator methods improvements

---

core/elements/ons-carousel.es6
core/elements/ons-navigator.es6
core/elements/ons-tabbar.es6
core/lib/animator-factory.es6
core/lib/doorlock.es6
core/lib/modal-animator.es6
core/lib/ons.es6
core/lib/tabbar-animator.es6

refactor(core): options default value

---

CHANGELOG.md
core/src/elements/ons-ripple.es6

@argelius Please review this when you have some time.

Ripple event fix

---

css-components/components-src/stylus/components/page.styl
css-components/www/theme.js

feat(css-components): Added Material background CSS.

---

CHANGELOG.md
core/src/elements/ons-navigator/fade-animator.es6

Fade animator was not working before.
@argelius This is also done.

Fade animator fix

---

CHANGELOG.md
core/css/common.css

Material input resize

---

core/src/elements/ons-navigator/ios-slide-animator.es6

Fixed #1131. @argelius Please merge this changes.

fix(ons-navigator): Fixed #1131.

---

core/src/elements/ons-dialog/index.js
css-components/components-src/stylus/components/dialog.styl

@argelius Related to #1161
Fixes it for `ons-dialog` but not for `ons-alert-dialog` yet.

fix(ons-dialog): Added dialog--material-mask

---

CHANGELOG.md
css-components/components-src/stylus/components/dialog.styl

Dialog container

---

core/src/elements/ons-alert-dialog/index.js
core/src/elements/ons-alert-dialog/index.spec.js
core/src/ons/notification.js
css-components/components-src/stylus/components/alert-dialog.styl
examples/alert_dialog/index.html

Alert dialog dom

---

CHANGELOG.md
core/src/elements/ons-fab.js
core/src/elements/ons-fab.spec.js
core/src/elements/ons-tabbar/index.js

@argelius This is done. As I mentioned #1184, page's `hide` event is fired slightly before but I think it's OK. The animation looks much nicer now :)

Fab animation

---

CHANGELOG.md
core/src/setup.js

Import order

---

core/src/elements/ons-tabbar/animator.js
core/src/elements/ons-tabbar/index.spec.js

@argelius With this,  `ons-fab` will display its show animation when tabbar's loadPage animation is `none`. Related to #1184

fix(ons-tabbar): NoneAnimator should be async.

---

test/e2e/navigator/index.html
test/e2e/navigator/scenarios.js

This adds a test for the "insertPage" function in ons-navigator, just resolving issue  #1233. The test tests both inserting a page at the front of the stack frame and just before the last element of the stack frame.

test(ons-navigator) add test for "insertPage" function #1233

---

core/src/elements/ons-navigator/index.js

fixes a simple spelling error in the documentation @anatoo is there anything else one needs to change?

fix(ons-navigator) correct spelling error in documentation

---

CHANGELOG.md
core/src/elements/ons-lazy-repeat.js
core/src/elements/ons-lazy-repeat.spec.js
core/src/ons/internal/lazy-repeat.js
core/src/ons/util.js

The first 3 issues are basically the same, the fourth has also been fixed in this commit, although ons-scroller will probably be removed soon anyway.

fix(ons-lazy-repeat): Fix #1236, #1029, #470 and #1035

---

CHANGELOG.md
bindings/angular1/js/notification.js
core/src/ons/notification.js

feat(ons.notification): Closes #1127

---

CHANGELOG.md
core/css/ripple.css
core/src/elements/ons-ripple/index.js
core/src/elements/ons-ripple/index.spec.js

@frankdiox This fixes the issue with the ripple. I have put `pointer-events: none` on the `.ripple` class and it's children so it shouldn't be able to block any clicks.
Actually while writing this message I noticed a small bug in the ripple so I will fix that as well :)

Fix ripple

---

core/src/elements/ons-tabbar/index.js

feat(ons-tabbar): Updates animation depending on attributes.

---

core/src/elements/ons-navigator/ios-slide-animator.js

@patrickklitzke 
I noticed that the background mask was not removed in the `pop()` method of the animator until after the callback is executed. This fixes that and another issue as well.

Fix slide anim

---

bindings/angular1/directives/page.js
bindings/angular1/views/page.js
core/src/elements/ons-page.js
core/src/elements/ons-page.spec.js
core/src/ons/util.js

Infinite scroll

---

core/src/ons/ons.js

@argelius Should we add this for debugging and showing examples?

feat(ons): Select platform from the URL.

---

CHANGELOG.md
core/src/elements/ons-splitter/index.js

fix(ons-splitter): Fixes #1300.

---

core/src/elements/ons-ripple/animator-css.js
core/src/elements/ons-ripple/animator-js.js
core/src/elements/ons-ripple/index.js
core/src/elements/ons-splitter-side.js
core/src/elements/ons-splitter-side.spec.js
core/src/elements/ons-splitter/index.spec.js
core/src/ons/device-back-button-dispatcher.js
core/src/ons/internal/animator-factory.js
core/src/ons/internal/internal.js
core/src/ons/ons.js
core/src/ons/ons.spec.js
core/src/ons/platform.js

@argelius I'm currently just resolving to `undefined` when the menu doesn't open for any reason and resolving to the element itself if it opens. Do you think this is enough or we should change it?

Splitter reject promises

---

core/src/elements/ons-navigator/index.js
core/src/elements/ons-navigator/ios-fade-animator.js
core/src/elements/ons-navigator/ios-lift-animator.js
core/src/elements/ons-navigator/md-slide-animator.js
core/src/ons/autostyle.js
core/src/ons/ons.js

@argelius Please merge this when you have some time.

Autostyle improvements

---

css-components/components-src/stylus/components/list.styl

@frankdiox This fixes the padding for material items. Can you check this and merge if it's OK?

fix(css-components): fix list item padding

---

core/src/elements/ons-scrollbar.js
core/src/elements/ons-scrollbar.spec.js

Trivial fix.
@argelius Merge this changes.

refactor(ons-scrollbar): Changed to use 'const' or 'let' instead of 'var'.

---

core/src/elements/ons-back-button.spec.js
core/src/elements/ons-list-item.js
core/src/elements/ons-list-item.spec.js
core/src/elements/ons-page.js
core/src/elements/ons-page.spec.js
core/src/elements/ons-toolbar.js
core/src/elements/ons-toolbar.spec.js
core/src/ons/base-element.js
core/src/ons/content-ready.js
core/src/ons/ons.js

Summary:
* Added contentReady() to wait child content filled.
* Make ons-page, ons-toolbar and ons-list-item Angular2 compatible.
@argelius Please review this changes and merge if there is no problems. I will make other all elements Angular2 compatible.

Make some elements Angular2 compatible.

---

CHANGELOG.md
core/src/elements/ons-splitter-side.js

fix(ons-splitter-side): Default side attribute and swipe-target-width.

---

CHANGELOG.md
core/src/elements/ons-back-button.js
core/src/elements/ons-back-button.spec.js
core/src/elements/ons-if.js
core/src/elements/ons-navigator/index.js
core/src/elements/ons-navigator/index.spec.js
core/src/elements/ons-page.js
core/src/ons/ons.js

@argelius @IliaSky This changes Navigator API and some other stuff. Please check if you like the new docs for navigator methods. I removed most of the repeated ones.

Navigator api refactor

---

CHANGELOG.md
core/src/elements/ons-navigator/index.js
core/src/elements/ons-navigator/ios-lift-animator.js
core/src/elements/ons-navigator/md-lift-animator.js

@IliaSky The animator was created before modifying `options.animation` :sweat_smile:

Navigator fix

---

core/vendor/viewport.js

@argelius Please take a look at this when you have time. Also, should I add this in 1.3.15 changelog? There is another important fix that needs to be released so I guess we can release 1.3.15 next week.

fix(viewport): Fixed viewport overwritten issue, closes #1357.

---

bindings/angular1/js/notification.js
core/src/ons/notification.js

@argelius I think this is what you said :)

feat(ons.notification): Improved API.

---

bindings/angular1/directives/keyboard.js
core/src/elements/ons-bottom-toolbar.js
core/src/elements/ons-fab.js
core/src/elements/ons-gesture-detector.js
core/src/elements/ons-lazy-repeat.js
core/src/elements/ons-pull-hook.js
core/src/elements/ons-splitter-content.js
core/src/elements/ons-splitter-side.js
core/src/elements/ons-splitter/index.js
core/src/elements/ons-tab.js
core/src/elements/ons-tabbar/index.js
core/src/elements/ons-toolbar-button.js
core/src/elements/ons-toolbar.js

@argelius I changed doc categories for some components. Please take a look. Here's the result:

docs(*): update doc categories

---

CHANGELOG.md
core/src/elements/ons-list-item.js
core/src/elements/ons-list-item.spec.js

@argelius take a look whether this works, i tested it.

feat(ons-list-item): Make the attribute `tappable` a boolean and add a property `tap-background-color`

---

core/src/elements/ons-range.js
core/src/elements/ons-range.spec.js
core/src/ons/content-ready.js
core/src/ons/content-ready.spec.js

@argelius Please merge this changes if there is no problems.

Make ons-range Angular2 compatible.

---

core/src/elements/ons-tab.js
core/src/elements/ons-tab.spec.js
core/src/elements/ons-tabbar/index.js
core/src/elements/ons-tabbar/index.spec.js
core/src/ons/content-ready.js
core/src/ons/content-ready.spec.js

@argelius Please merge this changes if there is no problems.

Make ons-tab and ons-tabbar angular2 compatible.

---

bindings/angular1/directives/ifOrientation.js
bindings/angular1/directives/ifPlatform.js
bindings/angular1/directives/slidingMenu.js
bindings/angular1/directives/splitView.js
core/src/elements/ons-back-button.js
core/src/elements/ons-button.js
core/src/elements/ons-fab.js
core/src/elements/ons-gesture-detector.js
core/src/elements/ons-if.js
core/src/elements/ons-input.js
core/src/elements/ons-lazy-repeat.js
core/src/elements/ons-pull-hook.js
core/src/elements/ons-range.js
core/src/elements/ons-ripple/index.js
core/src/elements/ons-speed-dial-item.js
core/src/elements/ons-speed-dial.js
core/src/elements/ons-switch.js
core/src/elements/ons-template.js
core/src/ons/gesture-detector.js

@argelius Please merge this PR, and the resulting doc will be look like below:

doc(*): update categories

---

npm-shrinkwrap.json

This should fix the error in circle ci, i am going to wait until the tests run through before merging.

chore(*): Updated npm-shrinkwrap.

---

core/src/elements/ons-if.js

@argelius Please merge this changes if there is no problems.

feat(ons-if): Make ons-if angular2 compatible.

---

CHANGELOG.md
core/src/elements/ons-speed-dial-item.js
core/src/elements/ons-speed-dial.js
core/src/lib/styler.js

@argelius Please merge this changes if there is no problem.

Make ons-speed-dial angular2 compatible.

---

CHANGELOG.md
core/src/elements/ons-pull-hook.js

@IliaSky Can you have a look at this? I guess it's enough but maybe you want it cleaner... :sweat_smile:

fix(ons-pull-hook): fixed-content attribute. Closes #1444.

---

CHANGELOG.md
core/src/elements/ons-navigator/index.js

@argelius This fixes the flickering in Microsoft Edge and should also fix #1430 (at least in Safari).

fix(ons-navigator): Closes #1430

---

CHANGELOG.md
core/src/onsenui-test.ts
core/src/onsenui.d.ts
gulpfile.babel.js
package.json

@argelius I think this should be enough.

chore(d.ts): Definitely typed.

---

bindings/angular2/src/directives/ons-alert-dialog.ts
bindings/angular2/src/directives/ons-carousel.ts
bindings/angular2/src/directives/ons-input.ts
bindings/angular2/src/directives/ons-lazy-repeat.ts
bindings/angular2/src/directives/ons-navigator.ts
bindings/angular2/src/directives/ons-page.ts
bindings/angular2/src/directives/ons-popover.ts
bindings/angular2/src/directives/ons-pull-hook.ts
bindings/angular2/src/directives/ons-range.ts
bindings/angular2/src/directives/ons-splitter.ts
bindings/angular2/src/directives/ons-switch.ts
bindings/angular2/src/directives/ons-tabbar.ts
docs/wcdoc/element.schema.json
docs/wcdoc/extra-element.schema.json
docs/wcdoc/index.js
docs/wcdoc/input.schema.json
docs/wcdoc/output.schema.json
docs/wcdoc/renderer.js
docs/wcdoc/validator.js

@argelius Please take a look at the change. This commit includes the modified doc build script with some added Angular 2 binding docs.

docs(angular2-binding): Add support for Angular 2 docs

---

CHANGELOG.md
core/src/ons/platform.js

@argelius Please check this when you have some free time.

fix(ons.platform): Closes #1482.

---

CHANGELOG.md
bindings/angular1/directives/fab.js
bindings/angular1/directives/speedDial.js
bindings/angular1/examples/fab/index.html
bindings/angular1/examples/speed_dial/index.html
bindings/angular1/views/fab.js
bindings/angular1/views/speedDial.js

@frankdiox Can you take a look at this when you have time?
I've added bindings for `<ons-fab>` and `<ons-speed-dial>`.

Add AngularJS 1.x bindings for `<ons-speed-dial>` and `<ons-fab>`. Closes #1485

---

.gitignore
CHANGELOG.md
core/src/elements/ons-page.js
core/src/elements/ons-page.spec.js

@argelius Please merge this changes if there is no problem.

Changed ons-page to accept ".content" and ".background" child elements.

---

core/css/input.css
core/src/elements/ons-input.js
core/src/elements/ons-input.spec.js
css-components/components-src/stylus/components/text-input.styl

@frankdiox Please take a look at this when you have time.
It solves this issue: https://github.com/OnsenUI/OnsenUI/issues/1505
Basically I use the colors defined in the theme instead of the color defined in the js.

Use theme color for MD input

---

CHANGELOG.md
bindings/angular2/examples/navigator.ts
bindings/angular2/src/directives/ons-navigator.ts
bindings/angular2/src/directives/ons-tabbar.ts
core/src/elements/ons-navigator/index.js
core/src/elements/ons-navigator/index.spec.js
core/src/elements/ons-page.js
core/src/elements/ons-tab.js
core/src/ons/page-loader.js

@argelius Please review and merge this changes when you have a time.
Summary:
* Changed ons-navigator to use page-loader.
* Removed `pushComponent()` and `popComponent()` on OnsNavigator directive.
* You can just use `pushPage()` and `popPage()` on OnsNavigatorElement with Angular2.

Changed ons-navigator to use page-loader and enabled ons-navigator on angular2.

---

bindings/angular2/src/directives/ons-navigator.ts
bindings/angular2/src/directives/ons-tabbar.ts
core/src/elements/ons-navigator/index.js
core/src/elements/ons-tab.js
core/src/ons/page-loader.js

@argelius Please merge this changes when you have a time.

Changed page-loader API slightly.

---

bindings/angular2/examples/pull-hook.ts
bindings/angular2/src/directives/ons-pull-hook.ts
core/src/elements/ons-pull-hook.js

@argelius Please review and merge this changes if there is no problem.
Added new implementation for ons-pull-hook directive. This changes enable to write the following code on ons-pull-hook:
```
<ons-pull-hook height="64px" threshold-height="128px" (changestate)="onChangeState($event)" (action)="onAction($event)">
{{message}}
</ons-pull-hook>
```

Added new directive for ons-pull-hook.

---

bindings/angular2/examples/navigator.spec.js
bindings/angular2/examples/navigator.ts
bindings/angular2/examples/splitter.ts
bindings/angular2/examples/tabbar.ts
bindings/angular2/src/directives/ons-navigator.ts
bindings/angular2/src/directives/ons-splitter.ts
bindings/angular2/src/directives/ons-tabbar.ts

@argelius Please merge this changes if there is no problem.

Removed deprecated ComponentResolver on angular2-binding.

---

bindings/angular1/directives/slidingMenu.js
bindings/angular1/directives/splitView.js
core/src/elements/ons-back-button.js
core/src/elements/ons-bottom-toolbar.js
core/src/elements/ons-button.js
core/src/elements/ons-fab.js
core/src/elements/ons-icon.js
core/src/elements/ons-input.js
core/src/elements/ons-lazy-repeat.js
core/src/elements/ons-modal/index.js
core/src/elements/ons-popover/index.js
core/src/elements/ons-progress-bar.js
core/src/elements/ons-progress-circular.js
core/src/elements/ons-pull-hook.js
core/src/elements/ons-range.js
core/src/elements/ons-ripple/index.js
core/src/elements/ons-speed-dial-item.js
core/src/elements/ons-speed-dial.js
core/src/elements/ons-splitter-content.js
core/src/elements/ons-splitter-side.js
core/src/elements/ons-splitter/index.js
core/src/elements/ons-switch.js
core/src/elements/ons-template.js
core/src/elements/ons-toolbar-button.js
core/src/elements/ons-toolbar.js

@argelius Updated categories for core lib.

Update reference categories.

---

bindings/angular2/package.json

@argelius Please merge this changes. I will release `rc1` after the merge.

chore(angular2-binding): Updated to angular-2.0.0.

---

bindings/angular2/src/directives/ons-input.ts
bindings/angular2/src/directives/ons-lazy-repeat.ts
bindings/angular2/src/directives/ons-navigator.ts
bindings/angular2/src/directives/ons-pull-hook.ts
bindings/angular2/src/directives/ons-range.ts
bindings/angular2/src/directives/ons-splitter.ts
bindings/angular2/src/directives/ons-switch.ts
bindings/angular2/src/directives/ons-tabbar.ts
bindings/angular2/src/ons/alert-dialog-factory.ts
bindings/angular2/src/ons/dialog-factory.ts
bindings/angular2/src/ons/modal-factory.ts
bindings/angular2/src/ons/notification.ts
bindings/angular2/src/ons/popover-factory.ts

@argelius @masahirotanaka Added codepen tags in Angular 2 binding. Merge this changes if there is no problem.

Add codepen tags in Angular 2 binding.

---

bindings/angular1/directives/ifOrientation.js
bindings/angular1/directives/ifPlatform.js
bindings/angular1/directives/slidingMenu.js
bindings/angular1/directives/splitView.js
bindings/angular1/templates/sliding_menu.tpl
bindings/angular1/templates/split_view.tpl
core/src/elements/ons-tab.js
core/src/elements/ons-tab.spec.js
core/src/elements/ons-tabbar/index.js
core/src/elements/ons-tabbar/index.spec.js

@argelius I removed "inner" suffix classes like "ons-tabbar-inner" or "ons-sliding-menu-inner". I think this "inner" suffix classes does not needed anymore. Please merge this changes if there is no problem.

Remove "inner" suffix classes.

---

CHANGELOG.md
core/src/ons/internal/lazy-repeat.js

@argelius Fixed #1613. Please merge this changes.

Fixed #1613.

---

CHANGELOG.md
bindings/angular1/views/switch.js
bindings/angular2/src/directives/ons-switch.ts
core/src/elements/ons-button.js
core/src/elements/ons-carousel.spec.js
core/src/elements/ons-list-header.js
core/src/elements/ons-list.js
core/src/elements/ons-page.js
core/src/elements/ons-popover/index.js
core/src/elements/ons-progress-bar.js
core/src/elements/ons-progress-bar.spec.js
core/src/elements/ons-progress-circular.js
core/src/elements/ons-progress-circular.spec.js
core/src/elements/ons-range.js
core/src/elements/ons-ripple/index.js
core/src/elements/ons-ripple/index.spec.js
core/src/elements/ons-switch.js
core/src/elements/ons-switch.spec.js
core/src/elements/ons-tab.js
core/src/elements/ons-toolbar-button.js
core/src/elements/ons-toolbar.js
package.json
test/e2e/switch/index.html

@argelius I removed all `_compiled` attributes from core. Please review this changes.

Removed "_compiled" attributes from core.

---

core/test/karma.conf.js
package.json

This PR adds support for unit testing on Safari and does not affects the CI.

Support unit testing on Safari.

---

CHANGELOG.md
core/vendor/microevent.js

@anatoo @frankdiox @asial-matagawa 
This fixes an issue in the event handling in AngularJS. Events were not removed correctly before.

Fix microevent

---

bindings/angular2/gulpfile.babel.js
bindings/angular2/package.json
bindings/angular2/src/angular2-onsenui.ts
bindings/angular2/src/directives/ons-lazy-repeat.ts
bindings/angular2/src/directives/ons-tabbar.ts
bindings/angular2/src/ons/notification.ts
bindings/angular2/src/ons/platform.ts
bindings/angular2/yarn.lock

Summary:
* Changed to reference "onsenui.d.ts" and removed unneeded "declare var ons: any;".
* Changed to include "onsenui.d.ts" in angular2-binding distribution.
@argelius Could you merge this changes if there is no problem?

Changed to include type definition file in Angular2 binding.

---

ISSUE_TEMPLATE.md

@argelius @frankdiox @anatoo 
Since `ISSUE_TEMPLATE.md` is so outdated, I have updated it.
Also, I have made a major changes on `Environment` section so that users can easily and precisely describe their environment.
Since this PR is just a proposal, if anyone feels this new template too redundant I will discard this PR and update the template in the same way as before.
What do you think of this proposal?

Update template and add more items into `Environment` section.

---

CHANGELOG.md
core/css/input.css
core/src/elements/ons-input.js
css-components/components-src/stylus/components/text-input.styl

@argelius `transparent` modifier and a simple fix for `float` attribute style.

Input style

---

circle.yml

This reverts commit 17a5e5f0dd9e320048843b330b38a085c8930e02.

Revert "fix(circle): rollback to yarn@0.16.1"

---

bindings/angular2/CHANGELOG.md
bindings/angular2/examples/pull-hook.ts
bindings/angular2/src/angular2-onsenui.ts

@asial-matagawa I changed module dependency in angular2-binding. I'm going to merge this changes to master branch.

 Changed to re-export BrowserModule.

---

CHANGELOG.md
bindings/angular1/test/e2e/backButton/scenarios.js
bindings/angular1/test/e2e/composition/navigator+dialog.html
bindings/angular1/test/e2e/composition/navigator+splitView.html
bindings/angular1/test/e2e/composition/scenarios.js
bindings/angular1/test/e2e/navigator/scenarios.js
bindings/react/CHANGELOG.md
bindings/react/demo/examples/ReduxNavigator/actions.js
bindings/react/demo/examples/ReduxNavigator/index.js
bindings/react/demo/examples/ReduxNavigator/main-page.js
bindings/react/demo/examples/ReduxNavigator/my-toolbar.js
bindings/react/demo/examples/ReduxNavigator/reducer.js
bindings/react/demo/examples/ReduxNavigator/secondary-page.js
bindings/react/demo/examples/RouterNavigator.js
bindings/react/demo/index.html
bindings/react/demo/index.js
bindings/react/package.json
bindings/react/src/RouterUtil.js
bindings/react/src/components/Navigator.jsx
bindings/react/src/components/RouterNavigator.jsx
bindings/react/src/index.js
bindings/react/webpack.config.js
bindings/react/yarn.lock
core/src/elements/ons-navigator/index.js
gulpfile.babel.js

@frankdiox 
This implements a stateless navigator. I have provided an example using Redux. As we discussed before, our library might be able to implement a higher order component to make this easier to use with Redux.

React new navigator

---

bindings/angular2/CHANGELOG.md
bindings/angular2/src/directives/ons-navigator.ts
core/src/elements/ons-navigator/index.js

Fixed #1730.

---

css-components/src/components/alert-dialog.less
css-components/src/components/button-bar.less
css-components/src/components/button.less
css-components/src/components/checkbox.less
css-components/src/components/dialog.less
css-components/src/components/fab.less
css-components/src/components/list.less
css-components/src/components/modal.less
css-components/src/components/navigation-bar.less
css-components/src/components/notification.less
css-components/src/components/popover.less
css-components/src/components/progress-bar.less
css-components/src/components/progress-circular.less
css-components/src/components/radio-button.less
css-components/src/components/range.less
css-components/src/components/search-input.less
css-components/src/components/switch.less
css-components/src/components/tabbar.less
css-components/src/components/text-input.less
css-components/src/components/textarea.less
css-components/src/components/toolbar-button.less

I fixed annotations on css-components for document generation on `onsen.io`. I will merge to master branch.

Fix annotations on css components.

---

bindings/angular2/CHANGELOG.md
bindings/angular2/examples/navigator.ts
bindings/angular2/src/directives/ons-input.ts
bindings/angular2/src/directives/ons-navigator.ts
bindings/angular2/src/directives/ons-range.ts
bindings/angular2/src/directives/ons-splitter.ts
bindings/angular2/src/directives/ons-switch.ts

I added `nativeElement` getter function to access DOM element on all directives. I will merge this changes to master.

Added `nativeElement` getter function to access DOM element on all directives.

---

core/src/elements/ons-select.js
examples/select/index.html

@frankdiox @asial-matagawa I provided a `select-id` attribute so that users can target the inner select, should be good to merge

Fix ons select

---

css-components/src/components/navigation-bar.less
css-components/src/components/search-input.less
css-components/src/components/text-input.less
css-components/src/components/textarea.less

Summary:
* Fixed broken search-input spacing on safari.
* Fixed annotations on some components.
* Changed default width on `.textarea` and `.text-input` components.
I will merge this changes to master.

Fix some broken css components.

---

css-components/components-src/stylus/components/select.styl

@anatoo I defined some variables for material select-input but in fact I'm not an expert so I have no idea if they're ok, can you check?

style(ons-select): Fixed material variables

---

css-components/src/components/button-bar.less
css-components/src/components/tabbar.less
css-components/src/components/text-input.less
css-components/templates/preview.html.eco

Summary:
* Fixed broken material tab-bar with icon and label.
* Fixed broken disabled text-input components.
* Fixed broken button-bar display on safari.
I will merge this changes to master branch.

Fixed some broken css components.

---

bindings/angular1/directives/input.js

@frankdiox @asial-matagawa Small fix for issue #1827, I'll merge it to master if you have no problem.

Angular1 input fix

---

CHANGELOG.md
core/src/elements/ons-tab.js
core/src/elements/ons-tab.spec.js

@frankdiox @anatoo Another user asked for this fix so I went ahead and did it, it's quite simple. Hope it's good 👍

fix(core): Fixes #1790 (active-icon attribute now working).

---

core/src/elements/ons-tab.js
core/src/elements/ons-tab.spec.js
core/src/ons/autostyle.spec.js

@frankdiox Here is the fix if you want to take a look before (re)merging 👍

fix(ons-tab): Fixes small bug on ons-tab and respective 'active-icon' attribute test passes.

---

core/src/elements/ons-progress-circular.js
core/src/elements/ons-progress-circular.spec.js
css-components/src/components/progress-circular.css

Simplified CSS progress-circular components. I will merge this change to master branch.

Refactored progress-circular CSS components.

---

core/src/elements/ons-fab.js
css-components/src/components/fab.css

Removed children selectors from fab CSS components. I will merge this changes to master branch.

Refactored fab CSS components.

---

core/src/elements/ons-progress-bar.js
core/src/elements/ons-progress-bar.spec.js
css-components/src/components/progress-bar.css

Removed children selectors from progress-bar components. I will merge this changes to master branch.

Refactored progress-bar CSS components.

---

CHANGELOG.md
core/src/elements/ons-range.js
core/src/elements/ons-range.spec.js
css-components/src/components/range.css

I refactored `range` css components and simplified internal DOM structure on `ons-range` components.
Old `ons-range`:
```html
<ons-range>
<div class="range__left" />
<input class="range" type="range" />
</ons-range>
```
New `ons-range`:
```html
<ons-range class="range">
<input class="range__input" type="range" />
</ons-range>
```
I will merge this changes to master branch if there is no problems.

Refactored range components.

---

css-components/src/components/button-bar.css

I will merge this changes to master branch.

refactor(css-components): Make selector declaration to MindBEMding style on "button-bar" components.

---

core/src/elements/ons-list-header.js
core/src/elements/ons-list-header.spec.js
core/src/elements/ons-list-item.js
core/src/elements/ons-list-item.spec.js
css-components/src/components/list.css
examples/list/index.html

Summary:
* Split into list, list-item, list-header components from list component.
* Re-enabled tap animation on tappable modifier.
* Applied retina border on list components.
I will merge this changes.

Refactor list components.

---

core/src/elements/ons-switch.js
css-components/src/components/switch.css

refactor(css-components): Simplified css rules on switch components.

---

css-components/src/components/range.css

Fix broken material range display.

---

bindings/react/src/components/Page.jsx

I Added an onDeviceBackButton to wrap the core page 'onDeviceBackButton'. It's related to the #1850

feat: react binding page - device back button

---

core/src/elements/ons-carousel.js
core/src/elements/ons-carousel.spec.js

@anatoo This is just a simple check in case a drag event is done on a range slider inside carousel as pointed out in #1763. Hope it's good.

fix(ons-carousel): Fixes #1763.

---

examples/gesture_detector/index.html
examples/lazy_repeat/index.html

Small improvement of two core examples. I will merge it if there are no problems.

fix(examples): Small fix for two examples.

---

bindings/react/CHANGELOG.md
bindings/react/src/components/BaseDialog.jsx
bindings/react/src/components/Carousel.jsx
bindings/react/src/components/Input.jsx
bindings/react/src/components/Page.jsx
bindings/react/src/components/PullHook.jsx
bindings/react/src/components/Range.jsx
bindings/react/src/components/RouterNavigator.jsx
bindings/react/src/components/Select.jsx
bindings/react/src/components/SpeedDialItem.jsx
bindings/react/src/components/SplitterSide.jsx
bindings/react/src/components/Switch.jsx
bindings/react/src/components/Tabbar.jsx

Fix #1768.
@asial-matagawa @frandiox Can I merge this changes to master branch now?

Fix #1768.

---

css-components/src/components/range.css

Fixed #1862. I will merge this changes.

fix(css-components): Fixed #1862.

---

CHANGELOG.md
bindings/vue/examples/components/Carousel.vue
bindings/vue/examples/components/Dialogs.vue
bindings/vue/examples/components/Forms.vue
bindings/vue/examples/components/Tabbar.vue
core/src/elements/ons-navigator/ios-slide-animator.js
core/src/elements/ons-pull-hook.js
core/src/elements/ons-splitter/index.js
core/src/elements/ons-tabbar/index.js
core/src/ons/util.js

@asial-matagawa @misterjunio Please merge if there's no problem :)

Deep toolbar animation

---

CHANGELOG.md
core/css/common.css
core/src/elements/ons-fab.js
core/src/elements/ons-fab.spec.js
core/src/elements/ons-page.js
core/src/elements/ons-speed-dial.js
core/src/elements/ons-speed-dial.spec.js

@asial-matagawa This was fixed some time ago but somehow it was changed again. This fixes again the transitions with FAB/SpeedDial components.

fix(ons-fab): Page transition animation with fabs.

---

CHANGELOG.md
bindings/angular1/services/onsen.js

@frandiox Here is the fix for #1884 👍

fix(angular1): Fixes #1884.

---

CHANGELOG.md
core/src/ons/internal/lazy-repeat.js

@asial-matagawa This should be enough to fix lazy repeat :)

fix(lazy-repeat): Closes #1871, closes #1899.

---

css-components/src/components/button-bar.css
css-components/src/components/index.css
css-components/src/components/segment.css
css-components/src/components/toolbar.css
css-components/src/theme.css

I split into "button-bar" components and "segment" components from "button-bar" components. And added material segment components.
I will merge this changes to master branch.

Added segment components.

---

CHANGELOG.md
core/src/elements/ons-progress-circular.js
css-components/src/components/progress-circular.css

@asial-matagawa 
Fixed #1921. I will merge this changes if there is no problem.

fix(progress-circular): Fixed #1921.

---

bindings/react/src/components/Navigator.jsx

All public methods in the `Navigator` component return a promise except replacePage.

Return a promise from replacePage

---

CHANGELOG.md
bindings/angular1/js/onsen.js
core/src/elements/ons-navigator/index.js
core/src/elements/ons-navigator/index.spec.js
core/src/elements/ons-page.js
core/src/elements/ons-page.spec.js
core/src/elements/ons-splitter-content.spec.js
core/src/elements/ons-splitter-side.spec.js
core/src/elements/ons-tabbar/index.spec.js
core/src/ons/internal/internal.js
core/src/ons/ons.js
core/src/ons/ons.spec.js
gulpfile.babel.js
package.json
yarn.lock

ons.createElement

---

CHANGELOG.md
bindings/angular1/services/onsen.js

@asial-matagawa @misterjunio Back to <2.0.5 :clap: :tada:

fix(angular1): Closes #1854.

---

CHANGELOG.md
core/src/polyfills.js

Polyfill `Set` and `Map` in order to support old browsers.

---

CHANGELOG.md
core/src/ons/device-back-button-dispatcher.js

@asial-matagawa Please have a look at this. I think it should be enough.

fix(core): Remove for...of loop.

---

bindings/vue/CHANGELOG.md
bindings/vue/examples/components/Carousel.vue
bindings/vue/examples/components/Dialogs.vue
bindings/vue/examples/components/Fab.vue
bindings/vue/examples/components/Splitter.vue
bindings/vue/examples/components/Tabbar.vue
bindings/vue/package.json
bindings/vue/src/components/VOnsCarousel.vue
bindings/vue/src/components/VOnsSpeedDial.vue
bindings/vue/src/components/VOnsSplitterSide.vue
bindings/vue/src/components/VOnsTabbar.vue
bindings/vue/src/directives/VOnsModel.js
bindings/vue/src/mixins/common.js
bindings/vue/yarn.lock

Vue 2.3.0: sync modifier

---

core/src/elements/ons-splitter/reveal-animator.js

@asial-matagawa Ugly bug fixed :confetti_ball: There is already a similar line in changelog so I didn't add anything else.

fix(ons-splitter): Reveal animation init.

---

css-components/src/components/range.css

@frandiox I fixed #1964. Could you review this changes?

Fixed #1964.

---

css-components/src/components/action-sheet.css
css-components/src/components/page.css
css-components/src/components/util.css
css-components/templates/preview.html.eco

Fixed #1991. I will merge this changes if there is no problem.

fix(css-components): Fixed #1991.

---

CHANGELOG.md
css-components/src/components/notification.css
css-components/src/theme.css

Added "material" modifier on "notification" CSS components. I will merge this changes.

Added material notification.

---

core/src/ons/platform.spec.js
core/test/unit/browser-local_chrome_headless.js
core/test/unit/karma.conf.js
core/test/unit/setup.js
gulpfile.babel.js
package.json
yarn.lock

:raised_hands: 
@asial-matagawa Can you test this?

chore(unit): Use headless Chrome for unit testing.

---

css-components/gulpfile.js
css-components/src/components/search-input.css
css-components/src/components/select.css

This fix #2048. I will merge this changes.

fix(css-components): Fixed incorrect image path.

---

css-components/src/components/checkbox.css

Refined material checkbox animations. I will merge this changes.

feat(css-components): Refined an animation of material checkbox components.

---

CHANGELOG.md
core/src/elements/ons-tab.js
core/src/elements/ons-tabbar/index.js
core/src/elements/ons-tabbar/index.spec.js
package.json

This reverts commit 810bdae14d41505bcff6c37b33a93113a522f4dc.

Revert "refactor(ons-tabbar): Use visibility hidden."

---

css-components/src/components/range.css
css-components/src/theme.css

I will merge this changes if there is no problem.
New:
Old:

feat(css-components): Refined appearances of material range components.

---

core/src/elements/ons-range.js
css-components/src/components/range.css

Refined appearances of material range component again. I will merge this changes if there is no problem.
New:
Old:

Refined appearances of material range component again.

---

css-components/gulpfile.js
css-components/src/components/alert-dialog.css
css-components/src/components/button.css
css-components/src/components/fab.css
css-components/src/components/page.css
css-components/src/components/range.css
css-components/src/components/segment.css

I Fixed all stylelint warnings. I will merge this changes.

Fix css warnings.

---

core/src/elements/ons-navigator/ios-slide-animator.js
core/src/elements/ons-navigator/md-fade-animator.js
core/src/elements/ons-navigator/md-slide-animator.js
css-components/src/components/global.css

@masahirotanaka @asial-matagawa I refined default animations of navigator's page transition. Could you review this changes?

Refine animation of navigator transition.

---

core/css/common.css
core/src/elements/ons-navigator/ios-slide-animator.js

@anatoo Can you please have a look at these 2 commits and tell me what you think?
Do you remember what is the `margin-top: -1px` for exactly?

Page background and iOS slide refactor

---

CHANGELOG.md
css-components/src/components/checkbox.css
css-components/src/components/radio-button.css
css-components/src/components/range.css
css-components/templates/preview.html.eco

@frandiox @masahirotanaka I removed focus ring effects from some material components(ons-range, ons-checkbox, ons-radio-button).
I will merge this changes if there is no problem.

Removed focus ring effects from some material components.

---

CHANGELOG.md
core/src/elements/ons-back-button.js
core/src/ons/autostyle.js

Added ripple effects properly for ons-back-button. I will merge this changes if there is no problem.

Added ripple effects for ons-back-button.

---

bindings/react/src/components/Navigator.jsx

onDeviceBackButton is lost on Navigator component re-renders

fix device back button handler

---

bindings/react/CHANGELOG.md
bindings/react/src/components/BaseDialog.jsx
bindings/react/src/components/Modal.jsx
bindings/react/src/components/Navigator.jsx
bindings/react/src/components/Page.jsx
bindings/react/src/components/RouterNavigator.jsx
bindings/react/src/components/Splitter.jsx

Extends #1887 to all the components that implement device back button handlers.

React back button handler improvement

---

bindings/react/src/components/Navigator.jsx

Add swipeable and swipePop method to Navigator component.

Add swipePop to Navigator

---

bindings/react/src/components/Navigator.jsx

Revert "fix(react/navigator): remove unnecessary renderPage"

---

CHANGELOG.md
core/css/common.css
css-components/src/components/global.css
css-components/src/dark-theme.css
css-components/src/old-theme.css
css-components/src/theme.css

This fix #2227. I will merge this changes if there is no problem.

Fix #2227.

---

CHANGELOG.md
core/css/common.css
core/src/elements/ons-page.js
core/src/ons/internal/swiper.js
css-components/src/dark-theme.css

@frandiox @asial-matagawa 
In some cases, Onsen UI components make useless layer creation. Too many nested layers may break translate3d() animation in UIWebView.
In this PR, I removed some useless layer creation to fix #2231.
Could you merge this changes if there is no problem?

Fix #2231.

---

CHANGELOG.md
core/src/elements/ons-list-item.js

ons-list-item prevent-tap

---

CHANGELOG.md
core/src/elements/ons-pull-hook.js

feat(ons-pull-hook): Allow threshold-height lower than height.

---

bindings/react/examples/components/Input.js
bindings/react/src/components/Input.jsx

to be in conformance to React, see <https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes>
Follow-up to PR #2338

fix(react): change case of "readonly" prop to "readOnly"

---

bindings/react/src/components/BasicComponent.jsx

This fixes #2158.
See https://codepen.io/anon/pen/OQRKeW?editors=1111 to reproduce the error.

Update changed className correctly

---

README.md

Adding Discord Link to README.md

Adding Discord Link

---

CHANGELOG.md
core/src/elements/ons-splitter-side.js

fix(ons-splitter-side): Fix splitter animation causing error in React bindings.

---

CHANGELOG.md
core/src/elements/ons-popover/index.js

fix(ons-popover): Fix alignment of popover on non-full-width pages

---

.circleci/config.yml

Fixed typo in config.yml

---

CHANGELOG.md
bindings/react/src/components/Tabbar.jsx

feat(ons-tabbar): Add visible prop to React binding

---

css-components/src/iphonex-support/combination.css

This PR is to address issue #2420

Respect safe area margins inside Modal on iPhone X

---

CHANGELOG.md
core/src/elements/ons-list-item/index.js
core/src/ons/util.js
core/src/ons/util.spec.js

fix(list-item): Fix expandable item breaking with multiple compiles

---

bindings/react/src/components/BaseInput.jsx

This fixes the issue for us that I reported in #2418. I suspect there are other components with this issue. If this change looks interesting then I can find some time to review other components and to setup a proper reproducing example.

Fix Checkbox behaviour on multi-mount #2418

---

css-components/src/components/button.css

This PR fixes https://github.com/OnsenUI/OnsenUI/issues/2469.

fix(css): Fix button style for Firefox

---

CHANGELOG.md
core/src/elements/base/base-dialog.js
core/src/elements/ons-toast/index.js
core/src/elements/ons-toast/index.spec.js

fix(toast): Fix app closing when toast is shown and back button is pressed

---

CHANGELOG.md
core/src/elements/ons-list-item/index.js
core/src/elements/ons-list-item/index.spec.js

ons-list-item: Make lists defined inside expandable content behave

---

bindings/vue/CHANGELOG.md
bindings/vue/src/components/VOnsListItem.vue
core/src/elements/ons-list-item/index.js

fix(vue): update expanded prop when list item is expanded

---

core/src/ons/platform.js

This fixes the issue where the isIPhoneX() returns false for IPhone XR

Added Extra sizes for iphone XR #2540

---

CHANGELOG.md
core/src/ons/platform.js

Some additional commits for #2545 .

Additional commits for iPhone XS, XS Max, and XR support

---

LICENSE
package.json

- Updated package.json with valid license property and SPDX License
- Added the full license to LICENSE file
- Updated LICENSE copyright

Updated License with a Valid SPDX License

---

CHANGELOG.md
bindings/angular1/CHANGELOG.md
bindings/angular1/package.json
css-components/package.json
package.json

Full details of problem here:
https://github.com/dominictarr/event-stream/issues/116

chore(*): Avoid event-stream@3.3.6 vulnerability

---

CHANGELOG.md
core/src/elements/ons-fab.js
core/src/elements/ons-page.spec.js

fix(ons-fab): Don't automatically show fab if it was manually hidden

---

gulpfile.babel.js

fix(gulp): Include font imports at top of CSS file

---

bindings/angular2/CHANGELOG.md
bindings/angular2/examples/carousel.ts
bindings/angular2/examples/lazy-repeat.ts
bindings/angular2/examples/popover.ts
bindings/angular2/examples/pull-hook.ts
bindings/angular2/examples/segment.ts
bindings/angular2/examples/toast.spec.js
bindings/angular2/package-dist.json
bindings/angular2/package.json
bindings/angular2/tsconfig.dev.json
bindings/angular2/tsconfig.json
bindings/angular2/webpack.dev.config.js
bindings/angular2/webpack.prod.config.js
bindings/angular2/yarn.lock

- upgrade Angular to v8
- migrate `@ViewChild` in examples
- fix toast test
- add `mode` property to webpack configs

Support Angular v8

---

CHANGELOG.md
core/src/elements/base/base-input.js

fix(ons-input): Add spellcheck to list of attributes.

---

CHANGELOG.md
core/src/ons/notification.js

fix(notification): Make prompt callback run when submitOnEnter is false

---

bindings/vue/CHANGELOG.md
bindings/vue/src/components/VOnsNavigator.vue

fix(vue): Don't add page to page stack when navigator push is canceled

---

bindings/react/CHANGELOG.md
bindings/react/examples/components/GestureDetector.js
bindings/react/examples/components/index.js
bindings/react/src/components/GestureDetector.jsx
bindings/react/src/index.umd.js

Add GestureDetector to React bindings

---

CHANGELOG.md
css-components/src/components/fab.css

fix(ons-fab): Stop fab scrolling with viewport when wrapped

---

CHANGELOG.md
core/src/ons/notification.js

fix(ons.notification): Resolve toast when hide is called before timeout

---

CHANGELOG.md
core/src/ons/internal/internal.js
core/src/ons/platform.js
core/src/ons/platform.spec.js
core/src/onsenui.d.ts

fix(ons): Set status-bar-fill on iPadOS

---

CHANGELOG.md
core/src/ons/internal/swiper.js

fix(ons-carousel): Calculate correct active index on resize

---

CHANGELOG.md
core/src/elements/ons-navigator/index.js

fix(ons-navigator): Stop pushPage's callback being called by popPage

---

CHANGELOG.md
bindings/vue/src/setup.js
core/src/elements/base/base-dialog.js
core/src/elements/ons-pull-hook.js
core/src/elements/ons-splitter-mask.js
core/src/ons/index.js
core/src/ons/platform.js
core/src/ons/platform.spec.js
core/src/ons/util.js
core/src/onsenui.d.ts
core/src/setup.js
package-lock.json
package.json

Remove UIWebView support and FastClick

---

CHANGELOG.md
css-components/src/components/fab.css

fix(ons-fab): Position fab relative to tab page

---

bindings/vue/package-lock.json
bindings/vue/vue-onsenui-examples/package.json
bindings/vue/vue-onsenui-examples/src/components/Carousel.vue
bindings/vue/vue-onsenui-examples/src/components/Dialogs.vue
bindings/vue/vue-onsenui-examples/src/components/Fab.vue
bindings/vue/vue-onsenui-examples/src/components/Forms.vue
bindings/vue/vue-onsenui-examples/src/components/InfiniteScroll.vue
bindings/vue/vue-onsenui-examples/src/components/Lists.vue
bindings/vue/vue-onsenui-examples/src/components/Navigator.vue
bindings/vue/vue-onsenui-examples/src/components/NavigatorVuex.vue
bindings/vue/vue-onsenui-examples/src/components/Segment.vue
bindings/vue/vue-onsenui-examples/src/components/Splitter.vue
bindings/vue/vue-onsenui-examples/src/components/Tabbar.vue
bindings/vue/vue-onsenui-examples/src/components/TabbarKeepAlive.vue
bindings/vue/vue-onsenui-examples/src/main.js

Updates the examples app to use Vue 3. Bumps Vue dependencies and fixes code to use Vue 3 syntax.

Use Vue 3 for examples app

---

bindings/vue/vue-onsenui/CHANGELOG.md
bindings/vue/vue-onsenui/src/components/VOnsNavigator.vue

Replaces this.$children. It was remove in Vue 3.

fix(vue): Replace this.$children

---

bindings/vue/vue-onsenui/src/components/VOnsAlertDialog.vue
bindings/vue/vue-onsenui/src/components/VOnsDialog.vue
bindings/vue/vue-onsenui/src/components/VOnsPopover.vue
bindings/vue/vue-onsenui/src/mixins/common.js
bindings/vue/vue-onsenui/src/mixins/derive.js

Remove dialog-cancel event from Vue Components

---

CHANGELOG.md
core/src/elements/ons-list-item/index.js
core/src/elements/ons-list-item/index.spec.js
core/src/onsenui.d.ts
css-components/src/components/list.css

feat(ons-list-item): Add `expanded` attribute and property

---

CHANGELOG.md
core/src/elements/base/base-button.js

fix(ons-button): Allow form submission on submit key keypress

---

CHANGELOG.md
core/src/elements/ons-back-button.js
core/src/elements/ons-carousel.js
core/src/elements/ons-pull-hook.js
core/src/elements/ons-speed-dial.js
core/src/elements/ons-tab.js
core/src/elements/ons-tabbar/index.js
core/src/ons/util.js

Issue 2909

---

CHANGELOG.md
bindings/vue3/vue-onsenui/src/components/VOnsBackButton.vue
bindings/vue3/vue-onsenui/src/components/VOnsCarousel.vue
bindings/vue3/vue-onsenui/src/components/VOnsNavigator.vue
bindings/vue3/vue-onsenui/src/components/VOnsPage.vue
bindings/vue3/vue-onsenui/src/components/VOnsPullHook.vue
bindings/vue3/vue-onsenui/src/components/VOnsSpeedDial.vue
bindings/vue3/vue-onsenui/src/components/VOnsTab.vue
bindings/vue3/vue-onsenui/src/components/VOnsTabbar.vue
bindings/vue3/vue-onsenui/src/docs/VOnsCarousel.wcdoc
bindings/vue3/vue-onsenui/src/docs/VOnsPullHook.wcdoc
bindings/vue3/vue-onsenui/src/docs/VOnsTabbar.wcdoc

Issue 2906

---

css-components/src/components/alert-dialog.css
css-components/src/components/button-bar.css
css-components/src/components/button.css
css-components/src/components/checkbox.css
css-components/src/components/fab.css
css-components/src/components/radio-button.css
css-components/src/components/search-input.css
css-components/src/components/select.css
css-components/src/components/switch.css
css-components/src/components/tabbar.css
css-components/src/components/text-input.css
css-components/src/components/toolbar.css

Also removes some superfluous mixins.
Fixes #2938.

Force CSS components to use their block class

---

.circleci/config.yml
onsenui/esm/ons/util.js
package-lock.json
package.json
react-onsenui-examples/package.json
react-onsenui/karma.conf.js
react-onsenui/package.json

- Add dependencies that were temporarily removed
- Bump old dependencies
- Fix karma config file
- Fix bug discovered in core where properties defined with util helper methods were not configurable
- Switch react tests on in CI

Fix React testing setup

---

onsenui/docs/wcdoc/index.js
react-onsenui/src/components/Carousel.jsx
react-onsenui/src/components/Checkbox.jsx
react-onsenui/src/components/Input.jsx
react-onsenui/src/components/Navigator.jsx
react-onsenui/src/components/Popover.jsx
react-onsenui/src/components/Radio.jsx
react-onsenui/src/components/Range.jsx
react-onsenui/src/components/RouterNavigator.jsx
react-onsenui/src/components/SearchInput.jsx
react-onsenui/src/components/Select.jsx
react-onsenui/src/components/Splitter.jsx
react-onsenui/src/components/SplitterSide.jsx
react-onsenui/src/components/Switch.jsx

Fixes that are needed to get onsen.io website working again.

Onsen.io fixes

---

onsenui/scripts/unit-test.js

chore(*): Ensure unit tests exit with exit code 1 on failure

---

vue-onsenui-examples/src/components/Forms.vue
vue-onsenui/CHANGELOG.md
vue-onsenui/src/components/VOnsRange.vue
vue-onsenui/src/mixins/index.js
vue-onsenui/src/mixins/model.js
vue3-onsenui-examples/src/components/Forms.vue
vue3-onsenui/CHANGELOG.md
vue3-onsenui/src/components/VOnsRange.vue
vue3-onsenui/src/mixins/index.js
vue3-onsenui/src/mixins/model.js

fix(vue2/vue3): Model VOnsRange value as a number

---

vue3-onsenui-examples/src/components/Navigator.vue
vue3-onsenui/src/components/VOnsNavigator.vue

Fixes #2877.
Also fix duplicate keys when page pushed twice.

Vue 3: Add workaround for Vue extends bug 

---

package-lock.json
vue-onsenui-examples/package.json
vue-onsenui/package-lock.json
vue-onsenui/package.json

fix: add vuex to vue-onsenui-examples
